patients = ['patient_id',
            'study_id',
            'patient_dmp_id',
            'patient_cmo_id',
            'patient_darwin_id',
            'patient_isabl_id',
            # 'patient_first_name',
            # 'patient_middle_name',
            # 'patient_last_name',
            # 'patient_date_of_birth',
            'patient_age',
            'patient_gender',
            'patient_race',
            # 'patient_religion',
            # 'patient_residence_address_1',
            # 'patient_residence_address_2',
            # 'patient_residence_address_city',
            # 'patient_residence_address_state',
            # 'patient_residence_address_zip_code',
            # 'patient_residence_address_country',
            'primary_medical_oncologist_name',
            'primary_surgeon_name',
            'patient_cancer_type',
            'patient_cancer_type_code',
            'patient_diagnosis_date',
            'patient_overall_survival_status',
            'patient_overall_survival_date',
            'patient_progression_free_survival_status',
            'patient_progression_free_survival_date',
            'patient_num_recurrence_events',
            'patient_inclusion_date',
            'patient_exclusion_date',
            'patient_inclusion_exclusion',
            'patient_exclusion_comments',
            # 'patient_last_appointment_date',
            # 'patient_last_doctor_visit_date',
            # 'patient_last_admission_date',
            # 'patient_last_discharge_date',
            # 'patient_last_contact_date',
            # 'patient_last_chemo_date',
            # 'patient_last_radiation_date',
            # 'patient_last_surgery_date',
            # 'patient_last_treatment_date',
            # 'patient_lad_cp_lfu_dte',
            # 'patient_last_known_alive_date',
            'patients_complete'
            ]

consents = ['patient_consent_irb',
            'patient_consent_date',
            'patient_consent_location',
            'patient_consent_extra_blood_collection',
            'consents_complete',
            ]

sequencing_bulk_dna = ['bulkdna_facility',
                       'bulkdna_sequencing_sample_prep_date',
                       'bulkdna_sequencing_submission_date',
                       'bulkdna_sequencer_model',
                       'bulkdna_sequencing_kit',
                       'bulkdna_sequencing_status',
                       'bulkdna_accession_number',
                       'bulkdna_file_path',
                       'sequencing_bulk_dna_complete',
                       ]
